### ISSUE TITLE
Window autoclosed when I resize to max on left or right margin.

### ISSUE THREAD

**Issue by stolarek** [BossBele/cropzee#2]
Hi BossBele,
Nice plugin, I like it.
But is it normal, when I edit a picture the window is automatic closed when I resize it to max on left or right margin?
Or is it a bug?
Best regards
Damian

**Comment by BossBele** [comment]
Hello @stolarek , Thank you very much.
That isn't normal.
To fix it, increase the padding on the left and right sides so that the cursor/finger does not accidentally get to the outside of the modal while resizing.
I hope that fixes it.

Btw, check out the demo of the new release and tell me what you think about it. Contact me via adambeleko@gmail.com
